name: Search for bestdeepl

on:
  schedule:
    - cron: '0 0 * * *'  # 每天00:00运行
  workflow_dispatch:    # 允许手动启动

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp

    - name: Run script
      run: |
        python check.py

    - name: Commit and push if it's different
      run: |
        git config --local user.email "xiaoxiaofeihh@foxmail.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Update success_result.txt"
        # 使用PAT代替默认的GITHUB_TOKEN
        git push https://${{ secrets.GH_PAT }}:x-oauth-basic@github.com/xiaozhou26/serch_deeplx.git
