name: Search for bestdeepl

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨 0 点运行
  workflow_dispatch:    # 允许手动启动

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp

    - name: Run script
      run: |
        python check.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "${{ secrets.EMAIL }}"
        git config --local user.name "GitHub Action"
        git add success_result.txt
        git commit -m "Update success_result.txt"
        git remote set-url origin https://github-actions[bot]:${{ secrets.GH_PAT }}@github.com/xiaozhou26/serch_deeplx.git
        git push
        git push origin HEAD:main
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
