name: Search for bestdeepl

on:
  schedule:
    - cron: '0 0 * * *'  # Run at 0:00 every day
  workflow_dispatch:    # Allow manual start

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp

    - name: Run script
      run: |
        python check.py
    
    - name: Upload success_result.txt
      uses: actions/upload-artifact@v2
      with:
        name: success_result
        path: ./success_result.txt
